name: Update page with new data

on:
  schedule:
    - cron: '0 6 * * 1-5' # 18:00 in UTC+10, Mon-Fri
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Git
      uses: actions4git/setup-git@v1
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.8.8"
        enable-cache: true
    - name: Update bill data
      run: uv run python main.py
    - name: Add, commit, and push any changes
      run: git add .; git diff-index --quiet HEAD || git commit -m "Update bill data"; git push
