name: Update page with new data

on:
  schedule:
    - cron: '0 0,5,13 * * 1-5' # 12:00, 17:00, and 23:00 in UTC+10, Mon-Fri
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Git
      uses: actions4git/setup-git@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Update bill data
      run: python3 scraper.py
    - name: Add, commit, and push any changes
      run: git add .; git diff-index --quiet HEAD || git commit -m "Update bill data"; git push
