name: Update page with new data

on:
  schedule: # Run at 00:00 in melbourne/sydmey time
    - cron: '0 14 */2 * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml_html_clean beautifulsoup4 lxml requests_html termcolor pyppeteer
    - name: Get API data
      run: python3 scraper.py
    - name: Add, commit, and push
      uses: actions4git/add-commit-push@v1
